### ISSUE TITLE
数据预处理时huggingface无法连接如何解决

### ISSUE THREAD

**Issue by lizhidomg** [czy1999/TKGQA_Competition_Baseline#1]
raise LocalEntryNotFoundError(
huggingface_hub.utils._errors.LocalEntryNotFoundError: Connection error, and we cannot find the requested files in the disk cache. Please try again or make sure your Internet connection is on.

**Comment by czy1999** [comment]
网络原因，请尝试更换网络或者将预训练语言模型下载至本地使用
